// This module will contain SeaORM entities
// Generated by: sea-orm-cli generate entity
//
// To generate entities, run:
// sea-orm-cli generate entity -o src/models/entities --database-url $DATABASE_URL

pub mod entities;
