import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'

const dir = dirname(fileURLToPath(import.meta.url))

describe('PhantasiWorkbenchAdmin', () => {
  it('工作台管理面接手添加、RSSHub、订阅列表和 OPML', () => {
    const src = readFileSync(join(dir, 'PhantasiWorkbenchAdmin.tsx'), 'utf8')
    const page = readFileSync(join(dir, '../../../views/Phantasi.tsx'), 'utf8')
    assert.match(src, /<AddMode/)
    assert.match(src, /<RSSHubInstances layout="page"/)
    assert.match(src, /<EditSourceMode/)
    assert.match(src, /onRefreshSource/)
    assert.match(src, /shareRssAddress/)
    assert.match(src, /sourceRssShareUrl/)
    assert.match(src, /notesRssUrl/)
    assert.match(src, /getNotesRssSettings/)
    assert.match(src, /setNotesRssEnabled/)
    assert.match(src, /<SwitchItem/)
    assert.match(src, /<ButtonItem/)
    assert.match(src, /workbench-notes-rss/)
    assert.match(src, /notesRssShareable/)
    assert.match(src, /key: 'share'/)
    assert.match(src, /query\?: string/)
    assert.match(src, /onRemoveSources/)
    assert.match(src, /toolbarPlacement="filters"/)
    assert.match(src, /selectAll/)
    assert.match(src, /deleteSelected/)
    assert.match(src, /workbenchDeleteSelectedSourcesConfirm/)
    assert.match(src, /workbenchAssignCategory/)
    assert.match(src, /onAssignSources/)
    assert.doesNotMatch(src, /sourceSelect\.picked === 0/)
    assert.doesNotMatch(src, /search=\{\{/)
    assert.doesNotMatch(src, /key: 'refresh-all'/)
    assert.match(src, /filterGroups/)
    assert.match(src, /collectWorkbenchSourceCategories/)
    assert.match(src, /collectWorkbenchSourceKinds/)
    assert.match(src, /extraCategories/)
    assert.match(src, /listPickerCategories/)
    assert.match(src, /sourceTypeLabel/)
    assert.match(src, /phantasi\.category/)
    assert.doesNotMatch(src, /workbenchSourceBoard/)
    assert.doesNotMatch(src, /未分类/)
    assert.match(src, /workbenchSourceStatus/)
    assert.match(src, /workbench-sources/)
    assert.match(src, /workbench-add/)
    assert.match(src, /workbench-rsshub/)
    assert.match(src, /workbench-opml/)
    assert.doesNotMatch(src, /formOpen/)
    assert.match(page, /PhantasiWorkbenchAdmin/)
    assert.match(page, /useNoteTransfer/)
    assert.match(page, /feedsIo/)
    assert.doesNotMatch(src, /from ['"]\.\.\/skin\//)
  })
})
