# ============================================
# Myriad Clean Script (Windows PowerShell)
# ============================================
# Purpose: Delete all config files, database, cache and build files for fresh testing
# Warning: This operation is irreversible! All data will be permanently deleted!

Write-Host "=====================================" -ForegroundColor Red
Write-Host "  Myriad Clean Tool" -ForegroundColor Red
Write-Host "=====================================" -ForegroundColor Red
Write-Host ""
Write-Host "WARNING: This script will delete:" -ForegroundColor Yellow
Write-Host "  - Database data (drop and recreate schema)" -ForegroundColor Yellow
Write-Host "  - Backend build files (target/)" -ForegroundColor Yellow
Write-Host "  - Frontend build files (frontend/dist/)" -ForegroundColor Yellow
Write-Host "  - Cache files (backend/cache/)" -ForegroundColor Yellow
Write-Host "  - Environment config (backend/.env)" -ForegroundColor Yellow
Write-Host ""

# Confirm deletion
$confirmation = Read-Host "Are you sure to continue? This is irreversible! (yes/no)"
if ($confirmation -ne "yes") {
    Write-Host "Operation cancelled" -ForegroundColor Green
    Read-Host "Press Enter to exit"
    exit 0
}

Write-Host ""
Write-Host "Starting cleanup..." -ForegroundColor Cyan

# 1. Clear database data (keep container)
Write-Host "[1/6] Clearing database data..." -ForegroundColor Cyan
$dbRunning = docker ps --filter "name=myriad-postgres" --format "{{.Names}}" 2>$null
if ($dbRunning -eq "myriad-postgres") {
    Write-Host "  Dropping all tables and clearing migration history..." -ForegroundColor Gray
    # Drop all tables and seaql_migrations
    $dropTablesSQL = @"
DO `$`$ DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END `$`$;
"@
    docker exec myriad-postgres psql -U myriad -d myriad -c $dropTablesSQL 2>&1 | Out-Null
    Write-Host "  [OK] All database tables dropped successfully" -ForegroundColor Green
}
else {
    Write-Host "  [!] Database container not running" -ForegroundColor Yellow
}

# 2. Delete backend build files
Write-Host "[2/6] Deleting backend build files..." -ForegroundColor Cyan
$backendTarget = "backend/target"
if (Test-Path $backendTarget) {
    Remove-Item -Path $backendTarget -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "  [OK] Backend build files deleted" -ForegroundColor Green
}
else {
    Write-Host "  [-] Backend build files do not exist" -ForegroundColor Gray
}

# 3. Delete frontend build files
Write-Host "[3/6] Deleting frontend build files..." -ForegroundColor Cyan
$frontendDist = "frontend/dist"
if (Test-Path $frontendDist) {
    Remove-Item -Path $frontendDist -Recurse -Force
    Write-Host "  [OK] Frontend build files deleted" -ForegroundColor Green
}
else {
    Write-Host "  [-] Frontend build files do not exist" -ForegroundColor Gray
}

# 4. Delete cache files
Write-Host "[4/6] Deleting cache files..." -ForegroundColor Cyan
$cacheDir = "backend/cache"
if (Test-Path $cacheDir) {
    Get-ChildItem -Path $cacheDir -Filter "*.json" -ErrorAction SilentlyContinue | Remove-Item -Force
    Write-Host "  [OK] Cache files deleted" -ForegroundColor Green
}
else {
    Write-Host "  [-] Cache directory does not exist" -ForegroundColor Gray
}

# 5. Delete environment config file
Write-Host "[5/6] Deleting environment config..." -ForegroundColor Cyan
$envFile = "backend/.env"
if (Test-Path $envFile) {
    Remove-Item -Path $envFile -Force
    Write-Host "  [OK] .env file deleted" -ForegroundColor Green
}
else {
    Write-Host "  [-] .env file does not exist" -ForegroundColor Gray
}

# Extra cleanup: Delete root target/ (generated by flycheck)
$rootTarget = "target"
if (Test-Path $rootTarget) {
    Remove-Item -Path $rootTarget -Recurse -Force
    Write-Host "  [OK] Root target/ directory deleted" -ForegroundColor Green
}

Write-Host ""
Write-Host "=====================================" -ForegroundColor Green
Write-Host "  Cleanup Complete!" -ForegroundColor Green
Write-Host "=====================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Run '.\scripts\start.ps1' to start services" -ForegroundColor White
Write-Host "  2. Use the setup wizard to initialize database and create admin user" -ForegroundColor White
Write-Host "  (Database container is still running, all tables cleared)" -ForegroundColor Gray
Write-Host ""

# Prevent window from closing immediately
Read-Host "Press Enter to exit"
