/** 快捷访问浮窗中的服务商展示顺序（三语共用） */
export const AI_PROVIDER_GUIDE_ORDER = [
  'openrouter',
  'openai',
  'azureOpenAI',
  'gemini',
  'anthropic',
  'deepseek',
  'volcengine',
  'dashscope',
  'moonshot',
  'zhipu',
  'siliconflow',
  'groq',
  'xai',
  'mistral',
  'together',
  'fireworks',
  'perplexity',
  'minimax',
  'ollama',
  'cloudflare',
  'cohere',
  'nvidia',
  'tencentHunyuan',
  'baiduQianfan',
  'openaiCompatible',
] as const

export type AiProviderGuideId = (typeof AI_PROVIDER_GUIDE_ORDER)[number]
