import { expect, test } from '@playwright/test'

test('image address and click link edit independently, survive serialization and undo together', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('locale', 'en-US'))
  await page.route('**/api/**', route => route.fulfill({ json: {} }))
  await page.goto('/noteImageEditing.html')
  const image = page.locator('.phantasi-note__visual img')
  await image.click()
  await expect(page).toHaveURL(/noteImageEditing.html$/)
  await page.getByLabel('Image address', { exact: true }).fill('/note-editor-cover.svg?updated=1')
  await page.getByLabel('Click destination', { exact: true }).fill('https://example.test/new')
  await page.getByRole('button', { name: 'Apply image settings', exact: true }).click()
  await expect(page.locator('#markdown')).toHaveText('[![Cover](/note-editor-cover.svg?updated=1)](https://example.test/new)')
  await expect(image).toHaveAttribute('src', '/note-editor-cover.svg?updated=1')
  await expect(page.locator('.phantasi-note__visual a')).toHaveAttribute('href', 'https://example.test/new')
  await page.getByLabel('Click destination', { exact: true }).fill('')
  await page.getByRole('button', { name: 'Apply image settings', exact: true }).click()
  await expect(page.locator('.phantasi-note__visual a')).toHaveCount(0)
  await expect(image).toBeVisible()
  await page.locator('.phantasi-note__visual').press('ControlOrMeta+z')
  await expect(page.locator('#markdown')).toHaveText('[![Cover](/note-editor-cover.svg)](https://example.test/old)')
})

test('image controls remain inside a narrow viewport and reject unsafe destinations', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.addInitScript(() => localStorage.setItem('locale', 'en-US'))
  await page.route('**/api/**', route => route.fulfill({ json: {} }))
  await page.goto('/noteImageEditing.html')
  await page.locator('.phantasi-note__visual img').click()
  const bar = page.locator('.phantasi-note__blockbar--image')
  const bounds = await bar.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  await page.getByLabel('Click destination', { exact: true }).fill('javascript:alert(1)')
  await page.getByRole('button', { name: 'Apply image settings', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('#markdown')).toHaveText('[![Cover](/note-editor-cover.svg)](https://example.test/old)')
})
