/**
 * 统一图标导出
 * 从 react-icons 和 lucide-react 精确导入需要的图标，保持包体积最小化
 *
 * ⚠️ 重要：不要使用 import * as 语法，否则会导入整个图标库
 */

import type { LucideIcon } from 'lucide-react'
import type { IconType } from 'react-icons'
// ============================================================
// Lucide Icons (Lu*) - 用于 Brew 阅读器等现代 UI
// ============================================================
import {
  Activity as LuActivity,
  AlertCircle as LuAlertCircle,
  AlertTriangle as LuAlertTriangle,
  AlignJustify as LuAlignJustify,
  ArrowRight as LuArrowRight,
  ArrowUpDown as LuArrowUpDown,
  BarChart3 as LuBarChart3,
  Calendar as LuCalendar,
  Check as LuCheck,
  CheckCircle as LuCheckCircle,
  CheckSquare as LuCheckSquare,
  ChevronDown as LuChevronDown,
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronUp as LuChevronUp,
  ClipboardList as LuClipboardList,
  Clock as LuClock,
  Cloud as LuCloud,
  CloudFog as LuCloudFog,
  CloudRain as LuCloudRain,
  CloudSnow as LuCloudSnow,
  CloudSun as LuCloudSun,
  Copy as LuCopy,
  Crown as LuCrown,
  Database as LuDatabase,
  Download as LuDownload,
  Droplets as LuDroplets,
  Edit3 as LuEdit3,
  ExternalLink as LuExternalLink,
  Eye as LuEye,
  EyeOff as LuEyeOff,
  FileText as LuFileText,
  Folder as LuFolder,
  FolderOpen as LuFolderOpen,
  Gauge as LuGauge,
  GitFork as LuGitFork,
  Globe as LuGlobe,
  GripVertical as LuGripVertical,
  Headphones as LuHeadphones,
  Image as LuImage,
  Inbox as LuInbox,
  Info as LuInfo,
  Key as LuKey,
  Keyboard as LuKeyboard,
  Languages as LuLanguages,
  Leaf as LuLeaf,
  Link as LuLink,
  List as LuList,
  Loader2 as LuLoader2,
  Lock as LuLock,
  MessageCircle as LuMessageCircle,
  MessageSquare as LuMessageSquare,
  Mic as LuMic,
  Minus as LuMinus,
  MinusSquare as LuMinusSquare,
  Monitor as LuMonitor,
  Moon as LuMoon,
  MoreHorizontal as LuMoreHorizontal,
  Music as LuMusic,
  Music2 as LuMusic2,
  Newspaper as LuNewspaper,
  Package as LuPackage,
  Palette as LuPalette,
  Pause as LuPause,
  Play as LuPlay,
  Plus as LuPlus,
  RefreshCw as LuRefreshCw,
  Reply as LuReply,
  RotateCw as LuRotateCw,
  Rss as LuRss,
  Search as LuSearch,
  SearchX as LuSearchX,
  Send as LuSend,
  Server as LuServer,
  Settings as LuSettings,
  ShieldAlert as LuShieldAlert,
  ShieldCheck as LuShieldCheck,
  ShoppingCart as LuShoppingCart,
  Shuffle as LuShuffle,
  SkipBack as LuSkipBack,
  SkipForward as LuSkipForward,
  SlidersHorizontal as LuSlidersHorizontal,
  SortAsc as LuSortAsc,
  Sparkles as LuSparkles,
  Square as LuSquare,
  Star as LuStar,
  Store as LuStore,
  Sun as LuSun,
  Sunrise as LuSunrise,
  Sunset as LuSunset,
  Tag as LuTag,
  Trash2 as LuTrash2,
  Type as LuType,
  Upload as LuUpload,
  User as LuUser,
  Users as LuUsers,
  Video as LuVideo,
  Volume2 as LuVolume2,
  Wind as LuWind,
  Wrench as LuWrench,
  X as LuX,
  Zap as LuZap,
  ZoomIn as LuZoomIn,
  ZoomOut as LuZoomOut,
} from 'lucide-react'

import { BsNintendoSwitch } from 'react-icons/bs'
// ============================================================
// Font Awesome Icons (Fa*) - 通用图标
// ============================================================
import {
  FaAlipay,
  FaAmazon,
  FaAnchor,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBars,
  FaBell,
  FaBellSlash,
  FaBlog,
  FaBolt,
  FaBook,
  FaBrain,
  FaBroadcastTower,
  FaBug,
  FaCalendar,
  FaCalendarAlt,
  FaCamera,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaClipboard,
  FaClock,
  FaCloud,
  FaCode,
  FaCodepen,
  FaCoffee,
  FaCog,
  FaComments,
  FaCompass,
  FaCompress,
  FaCopy,
  FaCrown,
  FaDatabase,
  FaDownload,
  FaEdit,
  FaEllipsisH,
  FaEllipsisV,
  FaEnvelope,
  FaExchangeAlt,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExpand,
  FaExternalLinkAlt,
  FaEye,
  FaEyeSlash,
  FaFeather,
  FaFileAlt,
  FaFilter,
  FaFire,
  FaFolder,
  FaFolderOpen,
  FaFreeCodeCamp,
  FaGamepad,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGripHorizontal,
  FaGripVertical,
  FaHdd,
  FaHeadphones,
  FaHeart,
  FaHistory,
  FaHome,
  FaImage,
  FaImages,
  FaInfoCircle,
  FaKey,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaLinkedin,
  FaList,
  FaLock,
  FaMagic,
  FaMicrophone,
  FaMoon,
  FaMountain,
  FaMusic,
  FaNewspaper,
  FaPaintBrush,
  FaPalette,
  FaPaperPlane,
  FaPause,
  FaPlay,
  FaPlayCircle,
  FaPlus,
  FaQuestionCircle,
  FaRedo,
  FaRobot,
  FaRocket,
  FaSave,
  FaSearch,
  FaServer,
  FaShoppingCart,
  FaSignInAlt,
  FaSignOutAlt,
  FaSlidersH,
  FaSnowflake,
  FaSort,
  FaSortDown,
  FaSortUp,
  FaSpinner,
  FaStar,
  FaSteam,
  FaSun,
  FaSync,
  FaSyncAlt,
  FaTerminal,
  FaTh,
  FaThLarge,
  FaTimes,
  FaTimesCircle,
  FaTools,
  FaTrash,
  FaTwitter,
  FaUmbrella,
  FaUndo,
  FaUnlink,
  FaUnlock,
  FaUpload,
  FaUser,
  FaUsers,
  FaVideo,
  FaVolumeUp,
  FaWater,
  FaWrench,
  FaXbox,
} from 'react-icons/fa'
// ============================================================
// Font Awesome 6 Icons (Fa6*) - 用于 FaGrip 等
// ============================================================
import { FaGrip } from 'react-icons/fa6'
// ============================================================
// Simple Icons (Si*) - 品牌图标
// ============================================================
import {
  SiAnilist,
  SiApple,
  SiArtstation,
  SiBaidu,
  SiBandcamp,
  SiBehance,
  SiBilibili,
  SiBitbucket,
  SiBlogger,
  SiBluesky,
  SiBuymeacoffee,
  SiCloudflare,
  SiDevdotto,
  SiDeviantart,
  SiDiscord,
  SiDouban,
  SiDribbble,
  SiEpicgames,
  SiFacebook,
  SiFigma,
  SiFlickr,
  SiGithub,
  SiGitlab,
  SiGoodreads,
  SiGoogle,
  SiGooglegemini,
  SiHashnode,
  SiHuggingface,
  SiInstagram,
  SiItchdotio,
  SiKaggle,
  SiKakaotalk,
  SiKofi,
  SiLastdotfm,
  SiLetterboxd,
  SiLine,
  SiMaildotru,
  SiMastodon,
  SiMedium,
  SiMisskey,
  SiMyanimelist,
  SiNaver,
  SiNeteasecloudmusic,
  SiNiconico,
  SiNotion,
  SiOdnoklassniki,
  SiOrigin,
  SiPatreon,
  SiPinterest,
  SiPixiv,
  SiPlaystation,
  SiProducthunt,
  SiQq,
  SiReddit,
  SiSinaweibo,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiStackoverflow,
  SiSteam,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTrakt,
  SiTumblr,
  SiTwitch,
  SiUnsplash,
  SiVk,
  SiWechat,
  SiWhatsapp,
  SiWordpress,
  SiX,
  SiXiaohongshu,
  SiYcombinator,
  SiYoutube,
  SiZhihu,
} from 'react-icons/si'

const SiCodepen = FaCodepen
const SiOpenai = FaRobot

const BangumiIcon: IconType = ({ size, style, title, ...props }) => {
  const iconSize = size ?? '1em'

  return (
    <svg
      viewBox="0 0 24 24"
      width={iconSize}
      height={iconSize}
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      style={{ verticalAlign: 'middle', ...style }}
      {...props}
    >
      {title ? <title>{title}</title> : null}
      <g
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M8.55 6.75 5.95 2.25" strokeWidth="2.15" />
        <path d="M15.45 6.75 18.05 2.25" strokeWidth="2.15" />
        <path
          d="M4.25 6.85h15.5A2.95 2.95 0 0 1 22.7 9.8v7.25A2.95 2.95 0 0 1 19.75 20H11.35L6.8 23.05 7.85 20h-3.6a2.95 2.95 0 0 1-2.95-2.95V9.8a2.95 2.95 0 0 1 2.95-2.95Z"
          strokeWidth="2.05"
        />
        <path d="m5.6 11.35 3.35 1.35-3.35 1.35" strokeWidth="1.45" />
        <path d="m18.4 11.35-3.35 1.35 3.35 1.35" strokeWidth="1.45" />
        <path d="M9.75 13.2h4.5L12 16.95Z" strokeWidth="1.35" />
      </g>
    </svg>
  )
}

const SiBangumi = BangumiIcon

const MyriadStoreIcon: IconType = ({ size, style, title, ...props }) => {
  const iconSize = size ?? '1em'

  return (
    <svg
      viewBox="0 0 24 24"
      width={iconSize}
      height={iconSize}
      role={title ? 'img' : undefined}
      aria-hidden={title ? undefined : true}
      xmlns="http://www.w3.org/2000/svg"
      style={{ verticalAlign: 'middle', ...style }}
      {...props}
    >
      {title ? <title>{title}</title> : null}
      <g
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        transform="translate(12 12) scale(1.16) translate(-12 -12)"
      >
        <path
          d="M6.55 5.35h10.9a1.85 1.85 0 0 1 1.78 1.35l.68 2.55H4.09l.68-2.55a1.85 1.85 0 0 1 1.78-1.35Z"
          strokeWidth="1.75"
        />
        <path
          d="M4.6 9.25v1.15a2.35 2.35 0 0 0 4.7 0V9.25"
          strokeWidth="1.75"
        />
        <path d="M9.3 9.25v1.15a2.7 2.7 0 0 0 5.4 0V9.25" strokeWidth="1.75" />
        <path
          d="M14.7 9.25v1.15a2.35 2.35 0 0 0 4.7 0V9.25"
          strokeWidth="1.75"
        />
        <path
          d="M5.75 13.25v4.45a1.95 1.95 0 0 0 1.95 1.95h8.6a1.95 1.95 0 0 0 1.95-1.95v-4.45"
          strokeWidth="1.75"
        />
      </g>
    </svg>
  )
}

// 导出 Simple Icons
export {
  SiAnilist,
  SiApple,
  SiArtstation,
  SiBaidu,
  SiBandcamp,
  BangumiIcon,
  SiBangumi,
  SiBehance,
  SiBilibili,
  SiBitbucket,
  SiBlogger,
  SiBluesky,
  SiBuymeacoffee,
  SiCloudflare,
  SiCodepen,
  SiDevdotto,
  SiDeviantart,
  SiDiscord,
  SiDouban,
  SiDribbble,
  SiEpicgames,
  SiFacebook,
  SiFigma,
  SiFlickr,
  SiGithub,
  SiGitlab,
  SiGoodreads,
  SiGoogle,
  SiGooglegemini,
  SiHashnode,
  SiHuggingface,
  SiInstagram,
  SiItchdotio,
  SiKaggle,
  SiKakaotalk,
  SiKofi,
  SiLastdotfm,
  SiLetterboxd,
  SiLine,
  SiMaildotru,
  SiMastodon,
  SiMedium,
  SiMisskey,
  SiMyanimelist,
  SiNaver,
  SiNeteasecloudmusic,
  SiNiconico,
  SiNotion,
  SiOdnoklassniki,
  SiOpenai,
  SiOrigin,
  SiPatreon,
  SiPinterest,
  SiPixiv,
  SiPlaystation,
  SiProducthunt,
  SiQq,
  SiReddit,
  SiSinaweibo,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiStackoverflow,
  SiSteam,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTrakt,
  SiTumblr,
  SiTwitch,
  SiUnsplash,
  SiVk,
  SiWechat,
  SiWhatsapp,
  SiWordpress,
  SiX,
  SiXiaohongshu,
  SiYcombinator,
  SiYoutube,
  SiZhihu,
  MyriadStoreIcon,
}

// 导出 Font Awesome
export {
  FaAlipay,
  FaAmazon,
  FaAnchor,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBars,
  FaBell,
  FaBellSlash,
  FaBlog,
  FaBolt,
  FaBook,
  FaBrain,
  FaBroadcastTower,
  FaBug,
  FaCalendar,
  FaCalendarAlt,
  FaCamera,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaClipboard,
  FaClock,
  FaCloud,
  FaCode,
  FaCoffee,
  FaCog,
  FaComments,
  FaCompass,
  FaCompress,
  FaCopy,
  FaCrown,
  FaDatabase,
  FaDownload,
  FaEdit,
  FaEllipsisH,
  FaEllipsisV,
  FaEnvelope,
  FaExchangeAlt,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExpand,
  FaExternalLinkAlt,
  FaEye,
  FaEyeSlash,
  FaFeather,
  FaFileAlt,
  FaFilter,
  FaFire,
  FaFolder,
  FaFolderOpen,
  FaFreeCodeCamp,
  FaGamepad,
  FaGem,
  FaGithub,
  FaGlobe,
  FaGraduationCap,
  FaGripHorizontal,
  FaGripVertical,
  FaHdd,
  FaHeadphones,
  FaHeart,
  FaHistory,
  FaHome,
  FaImage,
  FaImages,
  FaInfoCircle,
  FaKey,
  FaLeaf,
  FaLightbulb,
  FaLink,
  FaLinkedin,
  FaList,
  FaLock,
  FaMagic,
  FaMicrophone,
  FaMoon,
  FaMountain,
  FaMusic,
  FaNewspaper,
  FaPaintBrush,
  FaPalette,
  FaPaperPlane,
  FaPause,
  FaPlay,
  FaPlayCircle,
  FaPlus,
  FaQuestionCircle,
  FaRedo,
  FaRobot,
  FaRocket,
  FaSave,
  FaSearch,
  FaServer,
  FaShoppingCart,
  FaSignInAlt,
  FaSignOutAlt,
  FaSlidersH,
  FaSnowflake,
  FaSort,
  FaSortDown,
  FaSortUp,
  FaSpinner,
  FaStar,
  FaSteam,
  FaSun,
  FaSync,
  FaSyncAlt,
  FaTerminal,
  FaTh,
  FaThLarge,
  FaTimes,
  FaTimesCircle,
  FaTools,
  FaTrash,
  FaTwitter,
  FaUmbrella,
  FaUndo,
  FaUnlink,
  FaUnlock,
  FaUpload,
  FaUser,
  FaUsers,
  FaVideo,
  FaVolumeUp,
  FaWater,
  FaWrench,
  FaXbox,
}
export { FaGrip }

// 导出 Lucide Icons
export {
  LuActivity,
  LuAlertCircle,
  LuAlertTriangle,
  LuAlignJustify,
  LuArrowRight,
  LuArrowUpDown,
  LuBarChart3,
  LuCalendar,
  LuCheck,
  LuCheckCircle,
  // 选择 & 复选框
  LuCheckSquare,
  LuChevronDown,
  // 导航 & 方向
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuClipboardList,
  // 时间 & 用户
  LuClock,
  LuCloud,
  LuCloudFog,
  LuCloudRain,
  LuCloudSnow,
  LuCloudSun,
  LuCopy,
  LuCrown,
  LuDatabase,
  LuDownload,
  LuDroplets,
  LuEdit3,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileText,
  LuFolder,
  LuFolderOpen,
  LuGauge,
  LuGitFork,
  LuGlobe,
  LuGripVertical,
  LuHeadphones,
  LuImage,
  LuInbox,
  LuInfo,
  LuKey,
  LuKeyboard,
  LuLanguages,
  LuLeaf,
  LuLink,
  LuList,
  LuLoader2,
  LuLock,
  LuMessageCircle,
  LuMessageSquare,
  LuMic,
  LuMinus,
  LuMinusSquare,
  LuMonitor,
  LuMoon,
  LuMoreHorizontal,
  LuMusic,
  LuMusic2,
  LuNewspaper,
  LuPackage,
  LuPalette,
  LuPause,
  LuPlay,
  LuPlus,
  LuRefreshCw,
  LuReply,
  LuRotateCw,
  LuRss,
  LuSearch,
  LuSearchX,
  LuSend,
  LuServer,
  LuSettings,
  LuShieldAlert,
  LuShieldCheck,
  LuShoppingCart,
  LuShuffle,
  LuSkipBack,
  LuSkipForward,
  LuSlidersHorizontal,
  LuSortAsc,
  LuSparkles,
  LuSquare,
  LuStar,
  LuStore,
  LuSun,
  LuSunrise,
  LuSunset,
  LuTag,
  LuTrash2,
  LuType,
  LuUpload,
  LuUser,
  LuUsers,
  LuVideo,
  LuVolume2,
  LuWind,
  LuWrench,
  LuX,
  LuZap,
  LuZoomIn,
  LuZoomOut,
}

// ============================================================
// 别名
// ============================================================
export const FaXTwitter = SiX

// ============================================================
// 品牌图标别名 - 来自其他图标库
// ============================================================

/**
 * Nintendo Switch 品牌图标
 * Simple Icons 已移除此图标，使用 Bootstrap Icons 的 BsNintendoSwitch 替代
 */
export const SiNintendoswitch = BsNintendoSwitch

// ============================================================
// 图标映射表 - 用于动态查找 (getIconByName)
// ============================================================
export const iconMap: Record<string, IconType> = {
  // Simple Icons - 品牌图标
  SiSinaweibo,
  SiX,
  SiFacebook,
  SiInstagram,
  SiYoutube,
  SiTiktok,
  FaLinkedin,
  SiReddit,
  SiDiscord,
  SiTelegram,
  SiWhatsapp,
  SiSnapchat,
  SiPinterest,
  SiTwitch,
  SiSpotify,
  SiApple,
  SiAppstore: MyriadStoreIcon,
  MyriadStoreIcon,
  SiGoogle,
  FaAmazon,
  SiDouban,
  SiZhihu,
  SiQq,
  SiWechat,
  SiBaidu,
  SiXiaohongshu,
  SiGitlab,
  SiBitbucket,
  SiCodepen,
  SiDribbble,
  SiBehance,
  SiDeviantart,
  SiMedium,
  SiSubstack,
  SiPatreon,
  SiKofi,
  SiBuymeacoffee,
  SiMastodon,
  SiThreads,
  SiBluesky,
  SiMisskey,
  SiSoundcloud,
  SiBandcamp,
  SiItchdotio,
  SiPlaystation,
  SiNintendoswitch,
  SiEpicgames,
  SiOrigin,
  SiAnilist,
  SiMyanimelist,
  SiLetterboxd,
  SiTrakt,
  SiGoodreads,
  SiLastdotfm,
  SiPixiv,
  SiArtstation,
  SiFlickr,
  SiUnsplash,
  SiProducthunt,
  SiYcombinator,
  SiStackoverflow,
  SiDevdotto,
  SiHashnode,
  SiKaggle,
  SiHuggingface,
  SiFigma,
  SiNotion,
  SiNiconico,
  SiLine,
  SiKakaotalk,
  SiNaver,
  SiVk,
  SiOdnoklassniki,
  SiTumblr,
  SiWordpress,
  SiBlogger,
  SiGithub,
  SiSteam,
  SiNeteasecloudmusic,
  SiBilibili,
  SiMaildotru,
  // Font Awesome - 通用图标
  FaMusic,
  FaVideo,
  FaBroadcastTower,
  FaComments,
  FaGamepad,
  FaShoppingCart,
  FaNewspaper,
  FaCamera,
  FaBook,
  FaGraduationCap,
  FaGlobe,
  FaHome,
  FaStar,
  FaHeart,
  FaRocket,
  FaBolt,
  FaGem,
  FaCrown,
  FaFeather,
  FaLeaf,
  FaPaperPlane,
  FaCompass,
  FaAnchor,
  FaMoon,
  FaSun,
  FaCloud,
  FaFire,
  FaSnowflake,
  FaUmbrella,
  FaMountain,
  FaWater,
  FaCoffee,
  FaPlayCircle,
  FaBlog,
  FaAlipay,
  FaXbox,
  FaEdit,
  FaSave,
  FaTimes,
  FaPlus,
  FaSteam,
  FaTrash,
  FaCheck,
  FaExternalLinkAlt,
  FaExclamationCircle,
  FaChevronDown,
  FaChevronUp,
  FaExpand,
  FaCompress,
  FaChevronLeft,
  FaChevronRight,
  FaCog,
  FaUser,
  FaUsers,
  FaSearch,
  FaEye,
  FaEyeSlash,
  FaCopy,
  FaDownload,
  FaUpload,
  FaSync,
  FaSyncAlt,
  FaSpinner,
  FaInfoCircle,
  FaQuestionCircle,
  FaExclamationTriangle,
  FaCheckCircle,
  FaTimesCircle,
  FaRobot,
  FaBrain,
  FaHdd,
  FaLightbulb,
  FaTwitter,
  FaGithub,
  FaPlay,
  FaPause,
  // Font Awesome 6
  FaGrip,
  FaFreeCodeCamp,
  FaVolumeUp,
  FaMicrophone,
  FaHeadphones,
  FaClipboard,
  FaExchangeAlt,
  // 别名
  FaXTwitter: SiX,
}

/**
 * 根据名称获取图标组件
 * @param name 图标名称（如 "SiGithub", "FaHeart"）
 * @returns 图标组件或 null
 */
export function getIconByName(name: string): IconType | null {
  return iconMap[name] || null
}

// ============================================================
// 自定义 SVG 图标组件
// ============================================================

/**
 * RSSHub 品牌图标
 * 官方设计：地球 + 网状图案，代表全球化的 RSS 聚合
 * Simple Icons 中没有此图标，使用自定义 SVG
 */
export function RSSHubIcon({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
    </svg>
  )
}

// 为了兼容性，导出 NotionIcon 别名（使用 SiNotion）
export const NotionIcon = SiNotion

// 导出类型
export type { IconType, LucideIcon }
